declare enum UrlRequestFlags {
    UR_FLAG_NONE = 0,
    UR_FLAG_SKIP_CACHE = 1,
    UR_FLAG_ONLY_FROM_CACHE = 2,
    UR_FLAG_ALLOW_STORED_CREDENTIALS = 3,
    UR_FLAG_REPORT_UPLOAD_PROGRESS = 4,
    UR_FLAG_NO_DOWNLOAD_DATA = 5,
    UR_FLAG_NO_RETRY_ON_5XX = 6
}
