/**
 * Supported color types for menu items.
 */
declare enum MenuColorType {
  CEF_MENU_COLOR_TEXT = 0,
  CEF_MENU_COLOR_TEXT_HOVERED = 1,
  CEF_MENU_COLOR_TEXT_ACCELERATOR = 2,
  CEF_MENU_COLOR_TEXT_ACCELERATOR_HOVERED = 3,
  CEF_MENU_COLOR_BACKGROUND = 4,
  CEF_MENU_COLOR_BACKGROUND_HOVERED = 5,
  CEF_MENU_COLOR_COUNT = 6
}
