declare enum ContextMenuMediaStateFlags {
  CM_MEDIAFLAG_ERROR = 0,
  CM_MEDIAFLAG_PAUSED = 1,
  CM_MEDIAFLAG_MUTED = 2,
  CM_MEDIAFLAG_LOOP = 3,
  CM_MEDIAFLAG_CAN_SAVE = 4,
  CM_MEDIAFLAG_HAS_AUDIO = 5,
  CM_MEDIAFLAG_HAS_VIDEO = 6,
  CM_MEDIAFLAG_CONTROL_ROOT_ELEMENT = 7,
  CM_MEDIAFLAG_CAN_PRINT = 8,
  CM_MEDIAFLAG_CAN_ROTATE = 9
}
