declare enum EventFlags {
    EVENTFLAG_CAPS_LOCK_ON = 0,
    EVENTFLAG_SHIFT_DOWN = 1,
    EVENTFLAG_CONTROL_DOWN = 2,
    EVENTFLAG_ALT_DOWN = 3,
    EVENTFLAG_LEFT_MOUSE_BUTTON = 4,
    EVENTFLAG_MIDDLE_MOUSE_BUTTON = 5,
    EVENTFLAG_RIGHT_MOUSE_BUTTON = 6,
    // Mac OS-X command key.
    EVENTFLAG_COMMAND_DOWN = 7,
    EVENTFLAG_NUM_LOCK_ON = 8,
    EVENTFLAG_IS_KEY_PAD = 9,
    EVENTFLAG_IS_LEFT = 10,
    EVENTFLAG_IS_RIGHT = 11
}
